---
title: "iteration_and_listcols"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)

set.seed(1)
```

```{r}
l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary     = summary(rnorm(1000)))
```

```{r}
l$vec_numeric

l$summary

l[[2]]

mean(l$vec_numeric)
```

```{r}
## on class website it's a tibble but for purposes of class, it's now a list
df = list(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

df$a
```

```{r}
mean_and_sd <- function(input_x) {
  
    if (!is.numeric(input_x)) {
    stop("x should be numeric")
  } else if (length(input_x) < 3) {
    stop("x should be longer than 3")
  }
  
  tibble(
  mean_input = mean(input_x),
  sd_input = sd(input_x)
  )
}
```

```{r}
mean_and_sd(df[[1]])
mean_and_sd(df[[2]])
mean_and_sd(df[[3]])
mean_and_sd(df[[4]])
```

```{r}
output <- vector("list", length = 4)
```

Write first for loop

```{r}
for (i in 1:4) {
  
  output[[i]] = mean_and_sd(df[[i]])
  
}

output

##running this gives us the same output as the for loop and printing out the output
output <- map(df, mean_and_sd)

output_median <- map(df, median)

output_summary <- map(df, summary)
output <- map_dfr(df, mean_and_sd)

# explicitly saying what gets mapped
output <- map(df, ~mean_and_sd(.x))
```

## Revisiting Napoleon Dynamite

```{r}
read_page_reviews = function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  
  data_frame(title, stars, text)
}
```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_urls = str_c(url_base, 1:5)

output <- vector("list", length = 5)

for (i in 1:5) {
  
  output[[i]] = read_page_reviews(vec_urls[[i]])  

}

output <- map(vec_urls, read_page_reviews)
```

