---
title: "Writing Functions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
```

## Let's start

we're going to write some function

Z-scores
```{r}
x = rnorm(n = 30, mean = 4, sd = 2.3)
x_again = rnorm(n = 30, mean = 6, sd = 0.3)

(x - mean(x))/sd(x)
(x_again - mean(x_again)) / sd(x_again)
```

Here's the function
```{r}
z_score <- function(x) {
  
  if (!is.numeric(x)) {
    stop("x should be numeric")
  } else if (length(x) < 3) {
    stop("x should be longer than 3")
  }
  
  (x - mean(x)) / sd(x)
}
```

Try out the function
```{r}
z_score(x = x_again)

z_score(x = iris)
```

## Multiple outputs
```{r}
mean_and_sd <- function(input_x) {
  
    if (!is.numeric(input_x)) {
    stop("x should be numeric")
  } else if (length(input_x) < 3) {
    stop("x should be longer than 3")
  }
  
  tibble(
  mean_input = mean(input_x),
  sd_input = sd(input_x)
  )
}
```

```{r}
mean_and_sd(input_x = x)
```

## Multiple inputs

```{r}
sim_regression <- function(n){

sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}

sim_regression(n = 30)
```

```{r}
sim_regression <- function(n, beta0 = 2, beta1 = 3){

sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = beta0 + beta1 * x + rnorm(30, 0, 1)
)

  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
  
}

sim_regression(n = 3000, beta0 = 17, beta1 = -3)
sim_regression(3000, 2, 3)

```

## Scrape napolean
```{r}

```

